import type { CreatorCollaborationEngine } from "./creator-collaboration";

const esc = (value: unknown) => String(value ?? "").replace(/[&<>\"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[c] ?? c));

export function creatorCenterDashboard(engine: CreatorCollaborationEngine) {
  const creators = engine.rankCreators(50);
  const kits = engine.listSampleKits();
  return {
    ok: true,
    dataSource: "live",
    creators,
    kits,
    counts: {
      total: creators.length,
      approved: creators.filter((creator) => creator.status === "approved").length,
      performing: creators.filter((creator) => creator.status === "performing" || creator.status === "published").length,
      sampleKits: kits.length,
      pendingKits: kits.filter((kit) => !kit.approved).length,
    },
  };
}

export function creatorCenterHtml(): string {
  const style = `:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui;background:#09070d;color:#fff}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0%,#31132f,#09070d 42%),radial-gradient(circle at 100% 15%,#17143a,#09070d 45%)}main{max-width:1180px;margin:auto;padding:28px 22px 50px}.top{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:24px}.eyebrow{font-size:11px;letter-spacing:.16em;text-transform:uppercase;color:#c9bdd0}.title{font-size:30px;font-weight:850;letter-spacing:-.04em;margin-top:5px}.link{color:#ddd3df;text-decoration:none;border:1px solid #ffffff14;background:#ffffff08;padding:10px 14px;border-radius:12px;font-size:12px}.hero,.card{border:1px solid #ffffff12;border-radius:24px;background:#ffffff07;padding:22px}.hero{margin-bottom:16px}.hero h1{font-size:clamp(32px,5vw,52px);letter-spacing:-.055em;line-height:1;margin:0 0 12px}.hero p{color:#bcb0c1;line-height:1.6;max-width:780px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:16px 0}.metric{padding:16px;border:1px solid #ffffff0b;border-radius:16px;background:#09070d80}.metric small{display:block;color:#8f8493;font-size:11px}.metric strong{display:block;font-size:24px;margin-top:6px}.cols{display:grid;grid-template-columns:1.35fr .65fr;gap:16px}.row{padding:14px 0;border-bottom:1px solid #ffffff0b}.row:last-child{border-bottom:0}.name{font-weight:800}.meta{font-size:12px;color:#9f93a4;margin-top:5px}.badge{display:inline-block;padding:5px 8px;border-radius:999px;background:#ffffff0c;border:1px solid #ffffff12;font-size:11px;margin-top:8px}.empty{color:#9f93a4;font-size:13px;padding:18px 0}.policy{margin-top:16px;padding:14px;border-radius:14px;background:#ffb84a12;border:1px solid #ffb84a22;color:#e9d5ba;font-size:12px;line-height:1.5}@media(max-width:800px){.grid,.cols{grid-template-columns:1fr 1fr}}@media(max-width:520px){main{padding:18px 14px}.grid,.cols{grid-template-columns:1fr}.top{align-items:flex-start}}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Silku Creator Center</title><style>${style}</style></head><body><main><header class="top"><div><div class="eyebrow">Silku Marketing HQ</div><div class="title">Creator Center</div></div><a class="link" href="/dashboard">← Back to HQ</a></header><section class="hero"><div class="eyebrow">B6</div><h1>Creators ranked for beauty fit.</h1><p>Review creator profiles, score signals and sample-kit readiness from the durable Creator Collaboration layer. This first B6 surface is read-only; creator commitments remain explicit and approval-safe.</p></section><div class="grid"><div class="metric"><small>Total creators</small><strong id="total">—</strong></div><div class="metric"><small>Approved</small><strong id="approved">—</strong></div><div class="metric"><small>Performing</small><strong id="performing">—</strong></div><div class="metric"><small>Sample kits</small><strong id="kits">—</strong></div></div><section class="cols"><article class="card"><div class="eyebrow">Ranked creators</div><h2>Creator pipeline</h2><div id="creators" class="empty">Loading…</div></article><article class="card"><div class="eyebrow">Sample kits</div><h2>Product seeding</h2><div id="sampleKits" class="empty">Loading…</div></article></section><div class="policy">🛡️ Creator commitments are not auto-sent or auto-approved from this surface. The dashboard exposes persisted state and scoring only.</div></main><script>const esc=${esc.toString()};async function load(){const r=await fetch('/v1/creators/dashboard',{credentials:'same-origin',cache:'no-store'});if(r.status===401){location.href='/';return}const j=await r.json();if(!j.ok)throw new Error(j.error||'Creator Center unavailable');const c=j.counts;document.querySelector('#total').textContent=c.total;document.querySelector('#approved').textContent=c.approved;document.querySelector('#performing').textContent=c.performing;document.querySelector('#kits').textContent=c.sampleKits;document.querySelector('#creators').innerHTML=j.creators.length?j.creators.map((x,i)=>'<div class="row"><div class="name">#'+(i+1)+' '+esc(x.displayName)+'</div><div class="meta">'+esc(x.handle)+' · '+esc(x.platform)+' · '+esc(x.status)+'</div><span class="badge">Score '+esc(x.creatorScore??0)+'</span></div>').join(''):'<div class="empty">No creators in the pipeline yet.</div>';document.querySelector('#sampleKits').innerHTML=j.kits.length?j.kits.map(k=>'<div class="row"><div class="name">'+esc(k.kitId)+'</div><div class="meta">Creator: '+esc(k.creatorId)+' · Products: '+esc(k.productIds.length)+'</div><span class="badge">'+(k.approved?'Approved':'Pending approval')+'</span></div>').join(''):'<div class="empty">No sample kits created yet.</div>'}load().catch(e=>document.querySelector('#creators').textContent=e.message)</script></body></html>`;
}
